import os
from dotenv import load_dotenv

load_dotenv()
load_dotenv("environment.env", override=False)

AZURE_OPENAI_CHAT_API_KEY = os.getenv("AZURE_OPENAI_CHAT_API_KEY")
AZURE_OPENAI_CHAT_ENDPOINT = os.getenv("AZURE_OPENAI_CHAT_ENDPOINT")
AZURE_OPENAI_CHAT_DEPLOYMENT = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT")

AZURE_OPENAI_EMBEDDING_API_KEY = os.getenv("AZURE_OPENAI_EMBEDDING_API_KEY")
AZURE_OPENAI_EMBEDDING_ENDPOINT = os.getenv("AZURE_OPENAI_EMBEDDING_ENDPOINT")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT")

AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_KEY = os.getenv("AZURE_SEARCH_KEY")
AZURE_SEARCH_INDEX = os.getenv("AZURE_SEARCH_INDEX")

AZURE_BLOB_CONNECTION_STRING = os.getenv("AZURE_BLOB_CONNECTION_STRING")
AZURE_BLOB_CONTAINER = os.getenv("AZURE_BLOB_CONTAINER")

BLOB_CONT_PEND_FILE = os.getenv("BLOB_CONT_PEND_FILE", "Container Pendency Queue.xlsx")
BLOB_MAINT_LOG_FILE = os.getenv("BLOB_MAINT_LOG_FILE", "Maintenance Logs.xlsx")
BLOB_ROUTES_FILES = os.getenv("BLOB_ROUTES_FILES", "Routes.xlsx")
BLOB_STN_LDUNLD_TIME_FILE = os.getenv("BLOB_STN_LDUNLD_TIME_FILE","Stations Load Unload Time.xlsx")
BLOB_TRN_SCH_TRIPS_FILE = os.getenv("BLOB_TRN_SCH_TRIPS_FILE","Train Schedule Trips.xlsx")
BLOB_TRN_DATA_FILE = os.getenv("BLOB_TRN_DATA_FILE","Trains Data.xlsx")
